# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_fmindex', [dirname(__file__)])
        except ImportError:
            import _fmindex
            return _fmindex
        if fp is not None:
            try:
                _mod = imp.load_module('_fmindex', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _fmindex = swig_import_helper()
    del swig_import_helper
else:
    import _fmindex
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _fmindex.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _fmindex.SwigPyIterator_value(self)
    def incr(self, n=1): return _fmindex.SwigPyIterator_incr(self, n)
    def decr(self, n=1): return _fmindex.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _fmindex.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _fmindex.SwigPyIterator_equal(self, *args)
    def copy(self): return _fmindex.SwigPyIterator_copy(self)
    def next(self): return _fmindex.SwigPyIterator_next(self)
    def __next__(self): return _fmindex.SwigPyIterator___next__(self)
    def previous(self): return _fmindex.SwigPyIterator_previous(self)
    def advance(self, *args): return _fmindex.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _fmindex.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _fmindex.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _fmindex.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _fmindex.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _fmindex.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _fmindex.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _fmindex.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class IntVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _fmindex.IntVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _fmindex.IntVector___nonzero__(self)
    def __bool__(self): return _fmindex.IntVector___bool__(self)
    def __len__(self): return _fmindex.IntVector___len__(self)
    def pop(self): return _fmindex.IntVector_pop(self)
    def __getslice__(self, *args): return _fmindex.IntVector___getslice__(self, *args)
    def __setslice__(self, *args): return _fmindex.IntVector___setslice__(self, *args)
    def __delslice__(self, *args): return _fmindex.IntVector___delslice__(self, *args)
    def __delitem__(self, *args): return _fmindex.IntVector___delitem__(self, *args)
    def __getitem__(self, *args): return _fmindex.IntVector___getitem__(self, *args)
    def __setitem__(self, *args): return _fmindex.IntVector___setitem__(self, *args)
    def append(self, *args): return _fmindex.IntVector_append(self, *args)
    def empty(self): return _fmindex.IntVector_empty(self)
    def size(self): return _fmindex.IntVector_size(self)
    def clear(self): return _fmindex.IntVector_clear(self)
    def swap(self, *args): return _fmindex.IntVector_swap(self, *args)
    def get_allocator(self): return _fmindex.IntVector_get_allocator(self)
    def begin(self): return _fmindex.IntVector_begin(self)
    def end(self): return _fmindex.IntVector_end(self)
    def rbegin(self): return _fmindex.IntVector_rbegin(self)
    def rend(self): return _fmindex.IntVector_rend(self)
    def pop_back(self): return _fmindex.IntVector_pop_back(self)
    def erase(self, *args): return _fmindex.IntVector_erase(self, *args)
    def __init__(self, *args): 
        this = _fmindex.new_IntVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _fmindex.IntVector_push_back(self, *args)
    def front(self): return _fmindex.IntVector_front(self)
    def back(self): return _fmindex.IntVector_back(self)
    def assign(self, *args): return _fmindex.IntVector_assign(self, *args)
    def resize(self, *args): return _fmindex.IntVector_resize(self, *args)
    def insert(self, *args): return _fmindex.IntVector_insert(self, *args)
    def reserve(self, *args): return _fmindex.IntVector_reserve(self, *args)
    def capacity(self): return _fmindex.IntVector_capacity(self)
    __swig_destroy__ = _fmindex.delete_IntVector
    __del__ = lambda self : None;
IntVector_swigregister = _fmindex.IntVector_swigregister
IntVector_swigregister(IntVector)

class FM(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FM, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FM, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _fmindex.new_FM(*args)
        try: self.this.append(this)
        except: self.this = this
    def build(self, *args): return _fmindex.FM_build(self, *args)
    __swig_getmethods__["load"] = lambda x: _fmindex.FM_load
    if _newclass:load = staticmethod(_fmindex.FM_load)
    def save(self, *args): return _fmindex.FM_save(self, *args)
    def remap0(self, *args): return _fmindex.FM_remap0(self, *args)
    def count(self, *args): return _fmindex.FM_count(self, *args)
    def count_max_suffix(self, *args): return _fmindex.FM_count_max_suffix(self, *args)
    def locate(self, *args): return _fmindex.FM_locate(self, *args)
    def getSize(self): return _fmindex.FM_getSize(self)
    def extract(self, *args): return _fmindex.FM_extract(self, *args)
    def reconstructText(self, *args): return _fmindex.FM_reconstructText(self, *args)
    def getSizeN(self): return _fmindex.FM_getSizeN(self)
    __swig_destroy__ = _fmindex.delete_FM
    __del__ = lambda self : None;
FM_swigregister = _fmindex.FM_swigregister
FM_swigregister(FM)

def FM_load(*args):
  return _fmindex.FM_load(*args)
FM_load = _fmindex.FM_load

# This file is compatible with both classic and new-style classes.


